<?php

namespace backend\controllers;

use backend\models\Admin;
use Yii;
use backend\models\search\AdminSearch;

/**
 * Class AdminController
 *
 * @package \backend\controllers
 */
class AdminController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $this->setForward();
        $searchMmodel = new AdminSearch();
        $dataProvider = $searchMmodel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchMmodel,
            'dataProvider'=> $dataProvider,
        ]);
    }

    public function actionAdd()
    {
        $model = new Admin();
        if (Yii::$app->request->isPost) {
            $data = Yii::$app->request->post('Admin');
            $data['reg_time']   = time();
            $data['reg_ip']     = ip2long(Yii::$app->request->getUserIP());
            $data['last_login_time']    = 0;
            $data['last_login_ip']      = ip2long('127.0.0.1');
            $data['update_time']        = 0;
            $model->setAttributes($data);
            $model->generateAuthKey();
            $model->setPassword($data['password']);

            if ($model->save()) {
                $this->success('操作成功', $this->getForward());
            } else {
                $this->error('操作错误');
            }
        }
        return $this->render('add', ['model' => $model]);
    }
}